"""Compatibility namespace for canonical Core contracts."""
from tw_quant_core.market import (
    BarStatus,
    ConnectionStatus,
    DEFAULT_CALENDAR,
    ExecutionQuote,
    ExecutionQuoteCache,
    ExecutionQuoteView,
    ExecutionQuoteSink,
    KBar,
    TAIPEI,
    SUPPORTED_TIMEFRAMES,
    TIMEFRAME_LABELS,
    TIMEFRAME_MINUTES,
    TimeframeStreamAggregator,
    TickEvent,
    TradingCalendar,
    classify_tmf_session,
    aggregate_kbars,
    isoformat_millis,
    minute_floor,
    kbar_from_message,
    source_bar_limit,
    timeframe_bucket,
    validate_timeframe,
)
from .quote_store import SQLiteExecutionQuoteRepository
